### ISSUE TITLE
react.d.ts: Type mismatch error while using `connect` with Stateful Class React Component  

### ISSUE THREAD

**Issue by namankheterpal** [developit/unistore#103]
While using react ant typescript with unistore, we are unable use `connect` with stateful class components neither as a function call nor as a decorator.

There is type mismatch error as `react.d.ts` only has definition for stateless functional components only. Attached is the error I am getting:
![image](https://user-images.githubusercontent.com/18653130/42859198-26a27cbc-8a70-11e8-9fe3-6676081feff3.png)

**Comment by namankheterpal** [comment]
Fixed! I have sent the pull request #101 to update `react.d.ts` which will solve this issue. Please merge the same.

**Comment by developit** [comment]
Releasing!
