### ISSUE TITLE
App being rendered twice.

### ISSUE THREAD

**Issue by tonyatseven** [developit/unistore#115]
I'm not sure if it's a bug, or the way it has been implemented.

When building into env=production, it's rendering App twice.

index.js
```
import App from './components/app';
export default () => (
  <Provider store={store}>
    <NavEvents>
      <App/>
     </NavEvents>
  </Provider>
);
```

App component:

```
@connect(actions)
export default class App extends Component {
  handleRoute = event => {
    // XXX: Is this necessary? It was just part of the default preact template
    this.currentUrl = event.url;
  };

  render() {
    return (
        <div id="app">
          <a href="/" id="logo">
            Some link
          </a>
        </div>
    );
  }
}
```

<div id="app">...

is rendered twice onto the dom.

**Comment by developit** [comment]
@tonyatseven any chance this still happens when you remove `<NavEvents>` from the first component?

Otherwise a repo would be useful here - I'm not sure the issue is actually related to Unistore.

**Comment by tonyatseven** [comment]
No, sorry it wasn't related to unistore. It was happing from pre-render.  I was able to work around the issue by applying --no-prerender to the build.

```
NODE_ENV=production preact build --no-prerender --template src/template.hbbtv.html
```
