### ISSUE TITLE
`connect`ed components not updating on prop change

### ISSUE THREAD

**Issue by lwakefield** [developit/unistore#120]
[I set up an example here](https://codesandbox.io/s/3y87q0qlzp) in this example, I would expect that "I am thing: " is kept in sync with "count: ".

Given a connected component:

```javascript
@connect((state, props) => ({ thing: state.things[props.id] }))
class Thing extends Component {
  render() {
    return <div children={"I am thing: " + this.props.thing} />;
  }
}
```

I would expect that you could update `<Thing />` by passing in a new `props.id` - however the connected component is set up to only update the internal state when there is a change in the unistore - store instance: https://github.com/developit/unistore/blob/master/src/integrations/preact.js#L37.

Is it considered poor design to use connect to fetch state based on passed props?

Here is a proposed solution: https://github.com/developit/unistore/compare/master...lwakefield:master

**Comment by developit** [comment]
Ah this is definitely a bug. Prop changes should really rebind and reinvoke mapStateToProps.

**Comment by bastienrobert** [comment]
Hi @developit, you have some news ? 🙃

**Comment by lwakefield** [comment]
I can open https://github.com/developit/unistore/compare/master...lwakefield:master as a PR. It works, but I'm not fully sure of the implications though - it would probably need some more polish and tets.
