### ISSUE TITLE
State is mutable without calling store.setState

### ISSUE THREAD

**Issue by codesections** [developit/unistore#125]
My understanding is that one of the advantages of unistore/other state-management solutions is that state is immutable other than through calls to `setState`.  However, code such as the following will alter state:

```js
const Component = ({ array }) => {
  return (
    <div>
      {array.reverse().map((el) => (
          <span>{el}</span>
      ))}
    </div>
  );
};

export default connect('array')(Component);
```

Is that intended behavior or a bug?  If it is intended behavior, are there any patterns to ensure that my code does not mutate state other than through calls to `setState()`?

**Comment by developit** [comment]
@codesections you can use this middleware:

```
function makeStoreImmutable(store) {
  store.subscribe(state => {
    Object.freeze(state);
  });
}
```
