### ISSUE TITLE
Npm TypeScript declaration missing for unistore/devtools

### ISSUE THREAD

**Issue by scythianfuego** [developit/unistore#127]
npm unistore@3.1.0 release has a file devtools.d.ts missing (present in github zip)

**Comment by joseluisq** [comment]
Yep, https://github.com/developit/unistore/pull/112#issuecomment-436566004
I hope that maintainer provide missing `devtools.d.ts` soon.

**Comment by developit** [comment]
sorry about that!

**Comment by developit** [comment]
Bah - looked into it and I must have not noticed that the publish failed.  It's published to npm now as `3.1.1`.

**Comment by joseluisq** [comment]
👍

**Comment by joseluisq** [comment]
@developit at https://unpkg.com/unistore@3.1.1/ I see just the `devtools.js` file but not `devtools.d.ts`.

**Comment by developit** [comment]
Finally got this fixed in 3.2.1.

**Comment by joseluisq** [comment]
:1st_place_medal:
