### ISSUE TITLE
Type check errors when using StateMapper and actions

### ISSUE THREAD

**Issue by lauritzsh** [developit/unistore#137]
I am having trouble writing the correct types for injected props (the `I` generic from [here](https://github.com/developit/unistore/blob/master/preact.d.ts)). The problem is when I have to use both state mapping and actions, the injected props are saying missing props in the state mapper, but they are supplied from the actions.

An example would probably help:

```typescript
import createStore, { ActionCreator, BoundAction } from 'unistore';
import { connect } from 'unistore/preact';

const state = { count: 0 };
const store = createStore(state);

type Store = typeof store;

type StoreState = typeof state;

const actions: ActionCreator<StoreState> = (store: Store) => ({
  increment(state: StoreState) {
    return { count: state.count + 1 };
  }
});

type ComponentProps = {};

type ComponentState = {};

type InjectedProps = {
  count: number;
  increment: BoundAction;
};

connect<ComponentProps, ComponentState, StoreState, InjectedProps>(
  state => ({ count: state.count }),
  actions
);
```

Here I would expect the curried function to have a `props` that is joined by `ComponentProps` (in this example nothing) and `InjectedProps` (union of state mapper and actions) for the component.  However, the state mapping is giving an error:

```
Property 'increment' is missing in type '{ count: number; }' but required in type 'InjectedProps'.
```

This error makes sense to me since it's not satisfying the `InjectedProps` type. This is a contrived example so using a string such as `'count'` would work but I want to use the state mapper for type safety.

Right now I am putting the `increment: BoundAction` up in `ComponentProps` as an optional but this  makes me do an unnecessary `if (this.props.increment) { this.props.increment() }` check.

How would I write the typings such that it compiles fine? I made a [Gist](https://gist.github.com/lauritzsh/add6b949ee588602ed49eb99b773d3f0) just in case.

**Comment by LPVua** [comment]
@developit any updates on this one? seems like setting Partial<I> instead of I as return type of StateMapper fixes an issue (see: https://github.com/LPVua/unistore/commit/3c65cf5f1fdbd3893fe89543c4cee91e5d059c14)

**Comment by metonym** [comment]
I'm facing a similar situation, albeit the React integration and TypeScript.

Although not ideal, my current workaround is to assert the props of the wrapped component as an intersection between the `ComponentProps` and `InjectedProps` types.

```tsx
render() {
  const props = this.props as ComponentProps & InjectedProps;
}
```
