### ISSUE TITLE
What's the reason for peerDependencies?

### ISSUE THREAD

**Issue by Timer** [developit/unistore#139]
Hi! What's the reason for having `preact` and `react` listed as `peerDependencies` in the `*` range?

This creates some unnecessary noise for users installing the package in their projects.

Would you accept a pull request removing these?

**Comment by Timer** [comment]
Actually, I just realized that unistore has integrations and requires the peer dependencies for newer features (e.g. Yarn PnP).

Could we use the new RFC and make these optional?

https://github.com/yarnpkg/rfcs/pull/105

```json
{
  "peerDependencies": {
    "preact": "optional:*",
    "react": "optional:*"
  }
}
```

**Comment by NathanielHill** [comment]
Yes please. :pray:

**Comment by Timer** [comment]
Looks like I didn't catch the change to the RFC. Please see PR: https://github.com/developit/unistore/pull/142
