### ISSUE TITLE
On preact child elements get rendered before parent

### ISSUE THREAD

**Issue by d3x7r0** [developit/unistore#146]
I've been using preact + unistore for a small widget we're developing at work and got bitten by a small bit of behaviour that I'm not sure it can be classified as a bug.

The setup is this: I have a property in the store that tells me that something is loading. While that's happening my top level component will just render a loading screen but not the child components. Then, when that's done, the property gets set to false and the child gets re-rendered.

Then the problem is: the order of re-renders doesn't seem to be guaranteed so it's fairly common to see the child get rendered before the parent. [Here's an example in codesandbox](https://codesandbox.io/s/2xj7ww399j). The increment button has a timeout to simulate a network call, if you click it and look at the console you'll see a number attached to each line and you'll see that sometimes the child will get rendered after the parent. On firefox I can reliably see the behaviour after the second time I trigger the action.

Am I doing something wrong? Is this a bug or is it intended behaviour/a limitation of the library?

PS: I'm not sure if this also happens with react, so far I only tested it with preact but I'll try to see if the behaviour is the same for the former.

**Comment by developit** [comment]
This is an interesting one. What's supposed to happen is that store state -based updates trigger setState() based re-rendering for connected components, which all goes into a shared queue. Ideally those would be ordered, but there isn't any logic here that would guarantee such a thing.

I'm curious here to think about whether this ordering logic belongs in unistore, or in preact itself. If Preact were to order updates based on tree hierarchy, it could skip unnecessary intermediary state updates.

**Comment by d3x7r0** [comment]
If it helps in any way it looks like react-redux faced the same issue and [solved it on their connect implementation](https://github.com/reduxjs/react-redux/issues/509).

I've tried to take a small look at how they did it but I admit I couldn't really grasp it. I see that one point in time they kept a tree of subscriptions to ensure that they would always trigger down the tree but now I don't really get how it works. I'd have to try and setup a dummy project to debug and see if I could figure it out.

But yeah, leaving this to preact doesn't sound promissing. Since state updates are handled by a call to setState from the subscriptions how would one reliably figure out that you should skip updates?

**Comment by developit** [comment]
@d3x7r0 Just an update: Preact X now renders in order of tree depth, which should solve this issue.

**Comment by d3x7r0** [comment]
It does look like it clears up the problem on my [updated test case](https://codesandbox.io/s/elastic-sound-2w0td). Great news! Thanks for the heads up.

**Comment by developit** [comment]
Closing as this is now fixed :)
