### ISSUE TITLE
What's this mysterious ref in the CodeSandbox example? <App ref={ref} />

### ISSUE THREAD

**Issue by Birch-san** [developit/unistore#147]
Regarding the example: [README Example on CodeSandbox](https://codesandbox.io/s/l7y7w5qkz9)

What's with this mysterious bit:

```js
const ref = c => {
  if (!c) return c;
  console.log(c);
  // c.setState = c.forceUpdate;
  const s = c.setState;
  c.setState = function(a, b) {
    if (a==null) a = {};
    return s.call(this, a, b);
  };
};
```

Used later here:

```html
<App ref={ref} />
```

I think with unminified variable names, it might look like:

```js
const monkeyPatchSetState = component => {
  if (!component) {
    return component;
  }
  console.log(component);
  // component.setState = component.forceUpdate;
  const origSetState = component.setState;
  component.setState = function(state, props) {
    if (state == null) {
      state = {}
    };
    return origSetState.call(this, state, props);
  };
};
```

I found that if I remove that ref: my view never updates (even though I have a setInterval changing the store every second).

So, clearly this ref is important. Why's it promoting null state into an object? Is this the only and most recommended way to make the view update? Will I have to put this on every one of my child and grandchild components?

Here's my app (unistore 3.2.1, preact 10.0.0-alpha.2) where I update the store every second, from outside my component:

https://codesandbox.io/s/n9r3r0v83l?fontsize=14

If you attempt to remove the ref, you'll notice that the view ceases to update.

**Comment by developit** [comment]
Fixed + removed as per #148. Update to `unistore@3.4.1` and remove the workaround.
