### ISSUE TITLE
What's this mysterious prototype override in the CodeSandbox example? Provider.prototype.render

### ISSUE THREAD

**Issue by Birch-san** [developit/unistore#148]
Regarding the example: [README Example on CodeSandbox](https://codesandbox.io/s/l7y7w5qkz9)

What's with this mysterious bit:

```js
Provider.prototype.render = function(props) {
  return props.children;
};
```

If I remove that prototype override: the children don't get rendered.  
This seems important enough that it should be in the README.md, or even set as the default behaviour.

Here's my app (unistore 3.2.1, preact 10.0.0-alpha.2), which plays around with store (and updating store from outside of component):

https://codesandbox.io/s/r4l9lv8k5n?fontsize=14

**Comment by developit** [comment]
Ah - apologies, I accidentally overwrote the canonical sandbox instead of forking.

**Comment by developit** [comment]
I've removed the workarounds, since Preact 10.0.0-alpha.2 fixes both issues.
