### ISSUE TITLE
actions broken in latest iteration

### ISSUE THREAD

**Issue by cfenzo** [developit/unistore#15]
In the latest commit, the new `createAction` function calls the action in stead of returning a callable action-function.

PR on the way..

**Comment by cfenzo** [comment]
codesandbox with the bug here:
https://codesandbox.io/s/4w7omoq950

replace imported `./unistore2` with `./unistore` to see the old (2.2.0) behaviour, change to `./unistore3` to see the fix in the PR.

**Comment by developit** [comment]
Just released the fix in 2.4.0!
