### ISSUE TITLE
connect in React.FunctionComponent?

### ISSUE THREAD

**Issue by eduardoborges** [developit/unistore#173]
I am using typescript and I am trying to connect in the store.

I received the type error:

`Argument of type 'FunctionComponent<Props>' is not assignable to parameter of type '((props: unknown) => ReactNode) | ComponentClass<unknown, unknown>'.
  Type 'FunctionComponent<Props>' is not assignable to type '(props: unknown) => ReactNode'.
    Types of parameters 'props' and 'props' are incompatible.
      Type 'unknown' is not assignable to type 'PropsWithChildren<Props>'.
        Type 'unknown' is not assignable to type 'Props'.ts(2345)`

Any solution?

**Comment by developit** [comment]
I believe this is now fixed on master. Please let me know!

**Comment by arryanggaputra** [comment]
```
Argument of type '(props: LoginProps) => JSX.Element' is not assignable to parameter of type '((props: unknown) => ReactNode) | ComponentClass<unknown, unknown> | FC<unknown>'.
  Type '(props: LoginProps) => JSX.Element' is not assignable to type '(props: unknown) => ReactNode'.
    Types of parameters 'props' and 'props' are incompatible.
      Type 'unknown' is not assignable to type 'LoginProps'.

```
@developit do you have any suggestion?

**Comment by developit** [comment]
@arryanggaputra are you using React, or Preact?

**Comment by arryanggaputra** [comment]
@developit React Native 🙂
