### ISSUE TITLE
integration build seems broken.

### ISSUE THREAD

**Issue by MobiusHorizons** [developit/unistore#34]
The build appears to be broken for unistore 3.00. This can be seen here: https://codesandbox.io/s/9yk4lzm9xp

The problems as far as I can make out is that the `preact.js` file which gets built by microbundle has the text `module.exports=require('preact');` so while it does also export both `connect` and `Provider` none of these makes it through. 

I will hopefully look into this tomorrow, and try to provide a pull request if I figure it out.

**Comment by developit** [comment]
Fixed by updating to [microbundle@0.2.4](https://github.com/developit/microbundle/releases/tag/0.2.4).

**Comment by MobiusHorizons** [comment]
awesome!!
