### ISSUE TITLE
Issue with selectors as string

### ISSUE THREAD

**Issue by yeraycaballero** [developit/unistore#36]
Hi @developit 

I've just got an error passing a string to the select function. 
For this state = { a: 'b', c: 'd' }

```javascript 
select('a,c') // works fine 
```
```javascript 
select('a, c') // doesn't work. they key is ' c'
```

Given that the selector is or might be a string and it is not obvious that it should be csv without spaces on it. I was wondering if your consider worth it to trim the keys. Something like this

```javascript
export function select(properties) {
    if (typeof properties==='string') properties = properties.split(',').map(p => p && p.trim());
	return state => {
		let selected = {};
		for (let i=0; i<properties.length; i++) {
			selected[properties[i]] = state[properties[i]];
		}
		return selected;
	};
}
```

**Comment by developit** [comment]
We can fix this by passing a regex to split:

```js
properties = properties.split(/\s*,\s*/)
```

**Comment by yeraycaballero** [comment]
That's perfect!!. I have a util.test.js file if you want to include it
