### ISSUE TITLE
Require module not found - 'unistore/react'

### ISSUE THREAD

**Issue by ryami333** [developit/unistore#37]
Documentation suggests that you can import the react/preact-specific modules by:
```
import { connect, Provider } from 'unistore/react';
```
But this generates errors like 'required module not found'. I had a poke around `node_modules`, and there doesn't appear to be react/preact directories, so that would make sense:

<img width="155" alt="screen shot 2017-12-14 at 2 49 02 pm" src="https://user-images.githubusercontent.com/12481532/33971590-feb91c88-e0dd-11e7-9340-86041181a6ca.png">

**Comment by ryami333** [comment]
Gidday @developit, I see you've already implemented a fix for this - is there a release upcoming?

**Comment by developit** [comment]
It has been released, `3.0.3`.
