### ISSUE TITLE
Why calling actions in componentDidMount will not work？

### ISSUE THREAD

**Issue by lilijialiang** [developit/unistore#45]
I try to call the action in the lifecycle of componentDidMount, but it does not work. I want to know the reason, sorry to disturb.

[Example on CodeSandbox](https://codesandbox.io/s/914oy0pw74)

**Comment by developit** [comment]
Looks like we need to use `componentWillMount()` with an SSR check, since state is being mutated prior to the subscription being set up:
https://github.com/developit/unistore/blob/master/src/integrations/preact.js#L36
