### ISSUE TITLE
[Question] React Native support

### ISSUE THREAD

**Issue by alterx** [developit/unistore#47]
Just curious, does `unistore` support React Native? 
If so, are there any examples available?

**Comment by developit** [comment]
It runs in any environment that runs JavaScript. Examples would be the same as the Preact or standard React ones really, there's no difference.

**Comment by alterx** [comment]
Thanks for the quick response @developit, this is actually quite interesting and I thought the same but I just tested it on a CRNA + NativeBase project but the `connect` method seems to be broken:
```
ExceptionsManager.js:65 Invariant Violation: p(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```
Everything works as expected if I just use `redux-zero`'s  `connect` like this:
```
import { connect } from 'redux-zero/react';
//import { connect } from 'unistore/react';
```

**Comment by alterx** [comment]
Closing this is directly related to the bug reported in #50
