### ISSUE TITLE
Mistake in docs for createStore

### ISSUE THREAD

**Issue by JNaftali** [developit/unistore#5]
From the docs:
```javascript
let store = createStore();
   store.subscribe( state => console.log(state) );
   store.setState({ a: 'b' });   // logs { a: 'b' }
   store.setState({ c: 'd' });   // logs { c: 'd' }
```
I'm pretty sure that last line would actually log `{ a: 'b', c: 'd' }`

Apologies if this is my misunderstanding. Hate to make more work for you, awesome that you were able to make this so small!

**Comment by developit** [comment]
Whoops! It would yes. The example shows what would happen if the 2nd (`replace`) parameter were `true`.  I'll update the readme! :)
