### ISSUE TITLE
connect() is raising an error for React

### ISSUE THREAD

**Issue by vincentaudebert** [developit/unistore#50]
See PR https://github.com/developit/unistore/pull/49 for the tests and the error.

**Comment by ryami333** [comment]
I was unable to use Unistore with my React project either, can't remember whether the error was the same as yours but I think it was similar.

**Comment by ajainvivek** [comment]
I can't get in working on the project as well, look

Codesandbox: https://codesandbox.io/s/6462z4w663

Error:

`Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

**Comment by BilalBudhani** [comment]
I'm not able to get it working with React either https://stackblitz.com/edit/unistore-react.

**Comment by leecade** [comment]
same problem here.

**Comment by alterx** [comment]
Same here. I'm using react native tho, but got the same error. See https://github.com/developit/unistore/issues/47

**Comment by vincentaudebert** [comment]
@developit I had a try at fixing the issue. If you could review #49 / https://github.com/developit/unistore/pull/49/commits/79c167fe0cad72f3521119c99576f39d41ccf9fe

Thanks.

**Comment by vincentaudebert** [comment]
And that's https://github.com/developit/unistore/pull/49/commits/22240d2ee27cb16e14e8b9446c1af38ef0827a28

Note that I removed the part with `getState` for the subscribe/unsubscribe test (last one in the file)
I couldn't make it work with `mount()` and it's kind of covered with `builds.test.js` anyway

All yours @developit

**Comment by vincentaudebert** [comment]
Ok I think now we are done & dusted. https://github.com/developit/unistore/pull/49/commits/f2def88b8ebd0e19caeab244d3f8b9b52508ab20  :sweat_smile:

**Comment by kaheglar** [comment]
FYI specifically this is a error when setting the Wrapper prototype. 
`Wrapper.prototype = Object.create(Component)` should be `Wrapper.prototype = Object.create(Component.prototype)`.

**Comment by developit** [comment]
oh dear. I wish I could say that was the first time I'd done that by accident.

**Comment by timnovis** [comment]
Sadly also experiencing this issue today

**Comment by developit** [comment]
I'll get a patch fix out.

**Comment by dominiczaq** [comment]
Hey, any plans for releasing updated version anytime soon?

**Comment by developit** [comment]
it's going out today!

**Comment by alterx** [comment]
Aaaand it's out! :D
