### ISSUE TITLE
Access action return value?

### ISSUE THREAD

**Issue by gpoitch** [developit/unistore#53]
For example if an action returns a promise, I'd like to chain on to it after calling it.

```js
const actions = store => ({
  addItem(state, item) {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve({ items: [...state.items, item] })
      }, 500)
    })
  }
})

// elsewhere in component:
this.props.addItem('foo')
  // .then(() => console.log('done'))
```

Demo:
https://codesandbox.io/s/j43mkl31k3

**Comment by developit** [comment]
Only way to use the return value from an action is to pass it a callback, since action return values are state mutations. You could use a property in state as an indicator though:

```js
const actions = store => ({
  addItem(state, item) {
    store.setState({ done: false })
    return new Promise(resolve => {
      setTimeout(() => {
        resolve({ done: true, items: [...state.items, item] })
      }, 500)
    })
  }
})
```

Then make sure to subscribe to `done` and react to it in render.

Here's the callback variant:

```js
function callAction(action, ...args) {
  let result
  action( r => { result = r; }, ...args)
  return result
}

const actions = store => ({
  addItem(state, callback, item) {
    return callback(new Promise(resolve => {
      setTimeout(() => {
        resolve({ done: true, items: [...state.items, item] })
      }, 500)
    }))
  }
})

// in the component:
callAction(this.props.addItem, 'item').then( ... )
```

**Comment by gpoitch** [comment]
Cool, thanks.  A bunch of ways to do this (more state, callbacks, componentWillReceiveProps, etc), but I found chaining to the promise the cleanest way in this scenario.  Was hoping there was just a missing return somewhere 😁. Thanks for having a look!
