### ISSUE TITLE
TypeScript declaration missing for unistore/preact

### ISSUE THREAD

**Issue by goblindegook** [developit/unistore#57]
I'm getting the following error trying to include `connect` in TypeScript:

```
import { connect } from 'unistore/preact'
```

```
    TS7016: Could not find a declaration file for module 'unistore/preact'. '[...]/node_modules/unistore/preact.js' implicitly has an 'any' type.
  Try `npm install @types/unistore/preact` if it exists or add a new declaration (.d.ts) file containing `declare module 'unistore/preact';`
```

I imagine a similar declaration is required for React. The current definitions file declares `connect` in the base `unistore` module, however that module does not export the function.

**Comment by ascorbic** [comment]
Could there be an npm release with these changes, please.

**Comment by developit** [comment]
@ascorbic I believe this has been released.
