### ISSUE TITLE
Can't resolve 'unistore/devtools'

### ISSUE THREAD

**Issue by timnovis** [developit/unistore#61]
Hi, I'm trying to `import devtools from 'unistore/devtools';` with React and Unistore 3.0.3 and I'm getting `Can't resolve 'unistore/devtools'`

Is this a known issue?

**Comment by rinatkhaziev** [comment]
I don't think devtools are released in 3.0.3 - https://github.com/developit/unistore/tree/3.0.3

**Comment by jeberly** [comment]
You can install master with `npm install https://github.com/developit/unistore`.  The trouble I am having, is I don't see any changes to state in redux devtools even when using store.setState().  Has anyone got redux devtools showing state updates?

**Comment by developit** [comment]
I recall there being a PR for that?

**Comment by jeberly** [comment]
Thanks, It works on master.  Could you perhaps deploy new npm release so devtools integration works out of box when following readme?

**Comment by developit** [comment]
Released in 3.0.4!
