### ISSUE TITLE
Use `window.__REDUX_DEVTOOLS_EXTENSION__` instead of `window.devToolsExtension`

### ISSUE THREAD

**Issue by vdsabev** [developit/unistore#69]
I was <del>stealing</del> getting inspiration from some of the code in [devtools.js](https://github.com/developit/unistore/blob/e49018de35bec4d66d90672806668970ce9870b7/devtools.js#L2) to write the [devtools integration for derpy](https://github.com/vdsabev/derpy/blob/3a3d369ac8ae66ffaff89269080b096b496be340/debug/redux-devtools.ts). Thanks a lot for the inspiration 🙏

From what I read, newer versions of the extension use `window.__REDUX_DEVTOOLS_EXTENSION__` instead of `window.devToolsExtension`. Source:
- https://medium.com/@zalmoxis/redux-devtools-without-redux-or-how-to-have-a-predictable-state-with-any-architecture-61c5f5a7716f
- https://github.com/zalmoxisus/redux-devtools-extension#usage

> Note that starting from v2.7, `window.devToolsExtension` was renamed to `window.__REDUX_DEVTOOLS_EXTENSION__` / `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__`.

Perhaps I'm missing something - does `window.devToolsExtension` still work, or should unistore migrate to `window.__REDUX_DEVTOOLS_EXTENSION__` as well?

**Comment by wuweiweiwu** [comment]
@developit can I pick this issue up? :)

**Comment by developit** [comment]
Yes!
