### ISSUE TITLE
connect to multiple properties

### ISSUE THREAD

**Issue by bestwestern** [developit/unistore#70]
This is probably me not knowing enough about state managing - if so please provide link to where I can educate myself :) 
From readme:
```
let store = createStore({ count: 0 })
const App = connect('count', actions)(
```
But how do I do this: (it doesn't work)
```
let store = createStore({ count: 0, test: 2 })
const App = connect('count','test', actions)(
```

**Comment by bestwestern** [comment]
Argh of course!
connect can also take a function as a parameter, so the above is done like this:
`const App = connect(obj => ({ test: obj.test, count: obj.count }), actions)(`

**Comment by developit** [comment]
You can also use an array or comma-separated string of properties:

```js
let store = createStore({ count: 0, test: 2 })
const App = connect(['count','test'], actions)(

// or

let store = createStore({ count: 0, test: 2 })
const App = connect('count, test', actions)(
```

**Comment by bestwestern** [comment]
Even better! I thought I had tried that approach, but must have made a typeerror.
