### ISSUE TITLE
Outdated TypeScript definiton deployed?

### ISSUE THREAD

**Issue by screendriver** [developit/unistore#89]
On [line 8](https://github.com/developit/unistore/blob/master/index.d.ts#L8) you can see

```ts
export type Action<K> = (state: K, ...args: any[]) => void;
```

But when I install `unistore` 3.0.5 it looks like this in my `node_modules`

<img width="770" alt="screen shot 2018-05-24 at 11 14 26" src="https://user-images.githubusercontent.com/149248/40476302-fea69fce-5f43-11e8-96a8-a2ca45f1dbb2.png">

As you can see `...args: any[]` is missing here 🤔

**Comment by developit** [comment]
Good catch! I just released 3.0.6 that fixes this.
