### ISSUE TITLE
Cannot invoke passed function into child component with unistore

### ISSUE THREAD

**Issue by nukec** [developit/unistore#91]
Actions do work, when everything is in one initial file as shown in example in README, increment does increment. Now I am trying to pass action increment, into my child component as property(child component is App container):

    import { h, render, Component } from 'preact';
    import { Router, RouteProps, Route } from 'preact-router';
    import createStore from 'unistore';
    import { Provider, connect } from 'unistore/preact';
    import { State } from 'interfaces/unistore';
    
    // Import components
    import App from 'containers/app/app';
    
    // Create unitstore store
    const initialState = {
        count: 0,
        secondcount: 0,
        list: []
      }
      let store = createStore(initialState);
    
    // accept hot module update
    if ((module as any).hot) {
        (module as any).hot.accept();
    }
    
    // Add actions to store
    let actions = store => ({
        // for count
        increment(state) {
          return { count: state.count + 1 };
        },
        // for secondcount
        increment2: ({ secondcount }) =>({ secondcount: secondcount + 1}),
        
        // adds a todo item to the list array
        addTodo: (state, data)  => {
          return {
            ...state,
            list: [...state.list, data]
          }
        },
      });
    
    // Create higher order connect component
    const GlobalState = connect(["count", "secondcount", "list"], actions)(({ 
        count, secondcount, list, addTodo, increment, increment2 }) =>
    //     <div>
    //     <p>Count: {count}</p>
    //     <button onClick={increment}>Increment</button>
    //     <p>Second count: {secondcount}</p>
    //     <button onClick={increment2}>Increment</button>
    //   </div>
        <App {...{ count, secondcount, increment, increment2 }} />
    )
    
    // Bootstrap preact app
    render(<Provider store={store}><App  /></Provider>, document.getElementById('root'), document.getElementById('app'));
    
    // export a function to get the current unistore state
    export function getState() { return store.getState(); }

In app container I am then trying to access properties:

    // Import node modules
    import { h, render, Component } from 'preact';
    import { Router, RouteProps, Route, route } from 'preact-router';
    import createStore from 'unistore';
    import { connect } from 'unistore/preact';
    
    // Import internal modules
    import Navigation from 'components/navigation/navigation';
    import Home from 'containers/home/home';
    import Profile from 'containers/profile/profile';
    import Default from 'containers/default/default';
    import Signin from 'containers/signin/signin';
    import * as constants from 'helpers/constants';
    import { State } from "interfaces/unistore";
    
    interface IndexProps { count, secondcount, increment, increment2 }
    
    interface IndexState {}
    
    class InnerComponent extends Component<IndexProps, IndexState> {
    
        constructor(props) {
            super(props);
        }
    
        render() {
            return (
                    <div>
        <p>Count: {this.props.count}</p>
        <button onClick={this.props.increment}>Increment</button>
        <p>Second count: {this.props.secondcount}</p>
        <button onClick={this.props.increment2}>Increment</button>
      </div>
            )
        }
    }
    
    // Connect component to unistore store
    const Index = connect(["count", "secondcount", "increment", "increment2"])(({ count, secondcount, increment, increment2 }) => {
        return (
            <InnerComponent {...{ count, secondcount, increment, increment2 }} />
        )
    })
    
    // export the module
    export default Index;

Increment doesn't work now. What am I missing?

**Comment by developit** [comment]
Actions aren't bound in the first argument to `connect()`.  You should place them in a separate file and import them:

```js
// file: actions.js
export default store => ({
    // for count
    increment(state) {
      return { count: state.count + 1 };
    },
    // for secondcount
    increment2: ({ secondcount }) =>({ secondcount: secondcount + 1}),
    
    // adds a todo item to the list array
    addTodo: (state, data)  => {
      return {
        ...state,
        list: [...state.list, data]
      }
    },
  });
```

```js
// file: AppContainer.js
import actions from './actions';

class InnerComponent extends Component {
    render() {
      return (
        <div>
            <p>Count: {this.props.count}</p>
            <button onClick={this.props.increment}>Increment</button>
            <p>Second count: {this.props.secondcount}</p>
            <button onClick={this.props.increment2}>Increment</button>
          </div>
        )
    }
}

const Index = connect(["count", "secondcount"], actions)(props => (
    <InnerComponent {...{ count, secondcount, increment, increment2 }} />
))

export default Index;
```
